project:
  type: website

website:
  title: "Viet Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: About
      - pubs.qmd
      - notes.qmd
  twitter-card:
    creator: "@dragonstyle"
    site: "@rstudio"

format:
  html:
    theme: Simplex
    max-width: 2000px	
    linkcolor: "#16537e"
    toc-color: "#16537e"
    css: styles.css
    toc: true

theme:
  light: flatly
  dark: darkly